version: "3.9"

services:
  client:
    image: hiroki11hanada/service-unit:v1.0
    ports:
      - "8081:8080"
    volumes:
      - ./client/service-unit.yaml:/app/config/service-unit.yaml

  stateful-unit-mongo:
    image: hiroki11hanada/stateful-unit-mongo:v1.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mongo
    volumes:
      - ./data/db/:/data/db
