version: dev
name: redis-gateway
# deployment:
#   gateway: # load generator specific
#     virtualUsers: 3
#     duration: 60
adapters:
# redis secondary adapters
- server:
    action: read
    variant: rest
    route: redis
    weight: 1 # load generator specific
  tasks:
  - adapter:
      repository:
        name: redisrepo
        variant: redis
        action: read
        payload:
          variant: small

# redis secondary adapters
- server:
    action: write
    variant: rest
    route: redis
    weight: 1 # load generator specific
  tasks:
  - adapter:
      repository:
        name: redisrepo
        variant: redis
        action: write
        payload:
          variant: large
