---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - the-bench.hanapedia.link
  resources:
  - ingressadapters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - the-bench.hanapedia.link
  resources:
  - ingressadapters/finalizers
  verbs:
  - update
- apiGroups:
  - the-bench.hanapedia.link
  resources:
  - ingressadapters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - the-bench.hanapedia.link
  resources:
  - serviceunits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - the-bench.hanapedia.link
  resources:
  - serviceunits/finalizers
  verbs:
  - update
- apiGroups:
  - the-bench.hanapedia.link
  resources:
  - serviceunits/status
  verbs:
  - get
  - patch
  - update
