# permissions for end users to edit serviceunits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: serviceunit-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: the-bench-operator
    app.kubernetes.io/part-of: the-bench-operator
    app.kubernetes.io/managed-by: kustomize
  name: serviceunit-editor-role
rules:
- apiGroups:
  - service-unit.the-bench.hanapedia.link
  resources:
  - serviceunits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service-unit.the-bench.hanapedia.link
  resources:
  - serviceunits/status
  verbs:
  - get
