---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./deployment.yaml

configMapGenerator:
- name: lg-script
  files:
  - script.js

generatorOptions:
  disableNameSuffixHash: true
