version: dev
name: chain3
adapters:
- server:
    action: read
    variant: rest
    route: get
    payload: large
  steps: []
- server:
    action: write
    variant: rest
    route: post
  steps: []
