version: dev
name: chain1
adapters:
- server:
    action: read
    variant: rest
    route: get
    payload:
      variant: large
  tasks:
  - adapter:
      invocation:
        variant: rest
        service: chain2
        action: read
        route: get
- server:
    action: write
    variant: rest
    route: post
  tasks:
  - adapter:
      invocation:
        variant: rest
        service: chain2
        action: write
        route: post
        payload:
          variant: large
