version: dev
name: chain2
adapters:
- server:
    action: read
    variant: rest
    route: get
    payload: large
  steps:
  - adapter:
      invocation:
        variant: rest
        service: chain3
        action: read
        route: get
- server:
    action: write
    variant: rest
    route: post
  steps:
  - adapter:
      invocation:
        variant: rest
        service: chain3
        action: write
        route: post
        payload: large
