version: dev
name: rest-gateway
# deployment:
#   gateway: # load generator specific
#     virtualUsers: 3
#     duration: 60
adapters:
# http secondary adapters
- server:
    action: read
    variant: rest
    route: get
    weight: 1 # load generator specific
  tasks:
  - adapter:
      invocation:
        variant: rest
        service: chain1
        action: read
        route: get
- server:
    action: read
    variant: rest
    route: post
    weight: 1 # load generator specific
  tasks:
  - adapter:
      invocation:
        variant: rest
        service: chain1
        action: write
        route: post
        payload:
          variant: large
- server:
    action: read
    variant: rest
    route: fanout
    weight: 1 # load generator specific
  tasks:
  - adapter:
      invocation:
        variant: rest
        service: chain1
        action: write
        route: post
        payload:
          variant: large
  - adapter:
      invocation:
        variant: rest
        service: chain1
        action: read
        route: get
