version: "3.9"

services:
  gateway:
    image: hiroki11hanada/service-unit:v1.4
    ports:
      - "8081:8080"
    volumes:
      - ./fanout/gateway/service-unit.yaml:/app/config/service-unit.yaml

  fanout1:
    image: hiroki11hanada/service-unit:v1.4
    ports:
      - "8082:8080"
    volumes:
      - ./fanout/fanout1/service-unit.yaml:/app/config/service-unit.yaml

  fanout2:
    image: hiroki11hanada/service-unit:v1.4
    ports:
      - "8083:8080"
    volumes:
      - ./fanout/fanout2/service-unit.yaml:/app/config/service-unit.yaml

  fanout3:
    image: hiroki11hanada/service-unit:v1.4
    ports:
      - "8084:8080"
    volumes:
      - ./fanout/fanout3/service-unit.yaml:/app/config/service-unit.yaml
