version: "3.9"

services:
  gateway:
    image: hiroki11hanada/service-unit:v1.4
    ports:
      - "8081:8080"
    volumes:
      - ./chain/gateway/service-unit.yaml:/app/config/service-unit.yaml

  chain1:
    image: hiroki11hanada/service-unit:v1.4
    ports:
      - "8082:8080"
    volumes:
      - ./chain/chain1/service-unit.yaml:/app/config/service-unit.yaml

  chain2:
    image: hiroki11hanada/service-unit:v1.4
    ports:
      - "8083:8080"
    volumes:
      - ./chain/chain2/service-unit.yaml:/app/config/service-unit.yaml

  chain3:
    image: hiroki11hanada/service-unit:v1.4
    ports:
      - "8084:8080"
    volumes:
      - ./chain/chain3/service-unit.yaml:/app/config/service-unit.yaml
