version: "3.9"

services:
  gateway:
    image: hiroki11hanada/service-unit:v1.5
    ports:
      - "8081:8080"
    volumes:
      - ./chain/gateway/service-unit.yaml:/app/config/service-unit.yaml

  chain1:
    image: hiroki11hanada/service-unit:v1.5
    ports:
      - "8082:8080"
    volumes:
      - ./chain/chain1/service-unit.yaml:/app/config/service-unit.yaml

  load-generator:
    image: hiroki11hanada/tb-load-generator:v1.0
    volumes:
      - ./load-generator/load-generator/:/data
    ports:
      - "6565:6565"
    command: ["run", "--http-debug", "--out", "json=/data/result.json", "/scripts/script.js"]
