version: "3.9"

services:
  producer:
    image: hiroki11hanada/service-unit:v1.0
    ports:
      - "8081:8080"
    volumes:
      - ./kafka/producer/service-unit.yaml:/app/config/service-unit.yaml

  consumer:
    image: hiroki11hanada/service-unit:v1.0
    ports:
      - "8082:8080"
    volumes:
      - ./kafka/consumer/service-unit.yaml:/app/config/service-unit.yaml

  zookeeper:
    image: bitnami/zookeeper:3.8.1
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.4.0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092 # Listener to brokers from other network
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092 # Listener to brokers from the same network
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
