---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: consumer
  namespace: hexagon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: consumer
    spec:
      containers:
      - image: hiroki11hanada/service-unit:dev
        name: consumer
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: consumer-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: consumer
  namespace: hexagon
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 0
  selector:
    app: consumer
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    version: dev
    name: consumer
    adapters:
    - consumer:
        variant: kafka
        topic: topic1
      steps:
      - adapter:
          invocation:
            variant: rest
            service: chain1
            action: read
            route: get
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: consumer-config
  namespace: hexagon

