apiVersion: the-bench.the-bench.hanapedia.link/v1
kind: ServiceUnit
metadata:
  labels:
    app.kubernetes.io/name: serviceunit
    app.kubernetes.io/instance: serviceunit-sample
    app.kubernetes.io/part-of: the-bench-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: the-bench-operator
  name: serviceunit-sample
spec:
  # TODO(user): Add fields here
