apiVersion: v1
kind: Pod
metadata:
  name: curlpod
spec:
  containers:
  - name: curl-container
    image: curlimages/curl:latest
    command: ["/bin/sh", "-c", "while true; do { echo -e 'HTTP/1.1 200 OK\r\n'; } | nc -l -p 8080; done"]
