apiVersion: v1
kind: Pod
metadata:
  name: curlpod
spec:
  containers:
  - name: curl-container
    image: curlimages/curl:latest
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
