version: v1.0.6
name: shipping
adapters:
  - server:
      action: simpleRpc
      variant: grpc
      route: GetQuote
    tasks: []
  - server:
      action: simpleRpc
      variant: grpc
      route: ShipOrder
    tasks: []
