---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: gateway
  namespace: hexagon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway
    spec:
      containers:
      - image: hiroki11hanada/service-unit:dev
        name: gateway
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: gateway-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: gateway
  namespace: hexagon
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 0
  selector:
    app: gateway
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    version: dev
    name: gateway
    adapters:
    # kafka secondary adapter
    - server:
        action: read
        variant: rest
        route: topic1
        weight: 1 # load generator specific
      steps:
      - adapter:
          producer:
            variant: kafka
            topic: topic1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: gateway-config
  namespace: hexagon

