version: "3.9"

services:
  gateway:
    image: hiroki11hanada/service-unit:v1.0
    ports:
      - "8081:8080"
    volumes:
      - ./gateway/service-unit.yaml:/app/config/service-unit.yaml

  chain1:
    image: hiroki11hanada/service-unit:v1.0
    ports:
      - "8082:8080"
    volumes:
      - ./chain1/service-unit.yaml:/app/config/service-unit.yaml

  chain2:
    image: hiroki11hanada/service-unit:v1.0
    ports:
      - "8083:8080"
    volumes:
      - ./chain2/service-unit.yaml:/app/config/service-unit.yaml

  chain3:
    image: hiroki11hanada/service-unit:v1.0
    ports:
      - "8084:8080"
    volumes:
      - ./chain3/service-unit.yaml:/app/config/service-unit.yaml

  chain4:
    image: hiroki11hanada/service-unit:v1.0
    ports:
      - "8085:8080"
    volumes:
      - ./chain4/service-unit.yaml:/app/config/service-unit.yaml

  chain5:
    image: hiroki11hanada/service-unit:v1.0
    ports:
      - "8086:8080"
    volumes:
      - ./chain5/service-unit.yaml:/app/config/service-unit.yaml
