version: dev
name: cart
deployment:
  resources:
    requests:
      cpu: 200m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 128Mi
  env:
    - name: TRACING
      value: "false"
adapters:
  - server:
      action: simpleRpc
      variant: grpc
      route: GetCart
      payload:
        size: 18
    tasks:
      - adapter:
          repository:
            name: cartredis
            variant: redis
            action: read
            payload:
              size: 2
              variant: small
  - server:
      action: simpleRpc
      variant: grpc
      route: AddItem
      payload:
        size: 0
    tasks:
      - adapter:
          repository:
            name: cartredis
            variant: redis
            action: read
            payload:
              size: 18
              variant: small
      - adapter:
          repository:
            name: cartredis
            variant: redis
            action: write
            payload:
              size: 2
              variant: small
  - server:
      action: simpleRpc
      variant: grpc
      route: EmptyCart
      payload:
        size: 0
    tasks:
      - adapter:
          repository:
            name: cartredis
            variant: redis
            action: write
            payload:
              size: 1
              variant: small
