version: dev
name: currency
deployment:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  env:
    - name: TRACING
      value: "false"
adapters:
  - server:
      action: simpleRpc
      variant: grpc
      route: Convert
      payload:
        size: 16
    steps: []
  - server:
      action: simpleRpc
      variant: grpc
      route: GetSupportedCurrency
      payload:
        size: 100
    steps: []
