version: dev
name: email
deployment:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  env:
    - name: TRACING
      value: "false"
adapters:
  - server:
      action: simpleRpc
      variant: grpc
      route: SendOrderConfirmation
      payload:
        size: 0
    steps: []
