---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: chain3
  namespace: hexagon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chain3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chain3
    spec:
      containers:
      - image: hiroki11hanada/service-unit:dev
        name: chain3
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: chain3-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: chain3
  namespace: hexagon
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 0
  selector:
    app: chain3
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    version: dev
    name: chain3
    adapters:
    - server:
        action: read
        variant: rest
        route: get
        payload: large
      steps: []
    - server:
        action: write
        variant: rest
        route: post
      steps: []
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: chain3-config
  namespace: hexagon

