version: dev
name: chain1
adapters:
- server:
    action: read
    variant: rest
    route: get
    payload:
      variant: large
  steps: []
- server:
    action: write
    variant: rest
    route: post
  steps: []
