---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - generated/ad-service-unit.yaml
  - generated/cart-service-unit.yaml
  - generated/cartredis-stateful-unit.yaml
  - generated/checkout-service-unit.yaml
  - generated/currency-service-unit.yaml
  - generated/email-service-unit.yaml
  - generated/frontend-service-unit.yaml
  - generated/payment-service-unit.yaml
  - generated/productcatalog-service-unit.yaml
  - generated/recommendation-service-unit.yaml
  - generated/shipping-service-unit.yaml
