---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: grpc-gateway
  namespace: the-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grpc-gateway
    spec:
      containers:
      - image: hiroki11hanada/service-unit:dev
        name: grpc-gateway
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: grpc-gateway-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: grpc-gateway
  namespace: the-bench
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 0
  selector:
    app: grpc-gateway
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    version: dev
    name: grpc-gateway
    # deployment:
    #   gateway: # load generator specific
    #     virtualUsers: 3
    #     duration: 60
    adapters:
    # grpc secondary adapters
    - server:
        action: read
        variant: rest
        route: grpc
        weight: 1 # load generator specific
      steps:
      - adapter:
          invocation:
            variant: grpc
            service: grpcserver
            action: simpleRpc
            route: get
      - adapter:
          invocation:
            variant: grpc
            service: grpcserver
            action: clientStream
            route: get
      - adapter:
          invocation:
            variant: grpc
            service: grpcserver
            action: serverStream
            route: get
      - adapter:
          invocation:
            variant: grpc
            service: grpcserver
            action: biStream
            route: get
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: grpc-gateway-config
  namespace: the-bench

