---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: grpcserver
  namespace: the-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grpcserver
    spec:
      containers:
      - image: hiroki11hanada/service-unit:dev
        name: grpcserver
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: grpcserver-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: grpcserver
  namespace: the-bench
spec:
  ports:
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 0
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  selector:
    app: grpcserver
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    version: dev
    name: grpcserver
    adapters:
    - server:
        action: simpleRpc
        variant: grpc
        route: get
      steps: []
    - server:
        action: clientStream
        variant: grpc
        route: get
      steps: []
    - server:
        action: serverStream
        variant: grpc
        route: get
      steps: []
    - server:
        action: biStream
        variant: grpc
        route: get
      steps: []
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: grpcserver-config
  namespace: the-bench

