version: dev
name: cart
adapters:
- server:
    action: simpleRpc
    variant: grpc
    route: GetCart
  tasks:
  - adapter:
      repository:
        name: cartredis
        variant: redis
        action: read
        payload:
          variant: small

- server:
    action: simpleRpc
    variant: grpc
    route: AddItem
  tasks:
  - adapter:
      repository:
        name: cartredis
        variant: redis
        action: write
        payload:
          variant: small

- server:
    action: simpleRpc
    variant: grpc
    route: EmptyCart
  tasks:
  - adapter:
      repository:
        name: cartredis
        variant: redis
        action: write
        payload:
          variant: small
