version: dev
name: currency
adapters:
- server:
    action: simpleRpc
    variant: grpc
    route: Convert
  tasks: []
- server:
    action: simpleRpc
    variant: grpc
    route: GetSupportedCurrency
  tasks: []
