version: dev
name: productcatalog
adapters:
- server:
    action: simpleRpc
    variant: grpc
    route: ListProducts
  tasks: []
- server:
    action: simpleRpc
    variant: grpc
    route: GetProduct
  tasks: []
