version: dev
name: productcatalog
adapters:
- server:
    action: simpleRpc
    variant: grpc
    route: ListProducts
  steps: []
- server:
    action: simpleRpc
    variant: grpc
    route: GetProduct
  steps: []
