version: dev
name: recommendation
adapters:
- server:
    action: simpleRpc
    variant: grpc
    route: ListRecommendation
  tasks:
  - adapter:
      invocation:
        variant: grpc
        service: productcatalog
        action: simpleRpc
        route: ListProducts
