---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    rca: ignore
  creationTimestamp: null
  name: mongorepo
  namespace: hexagon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongorepo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongorepo
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_DATABASE
          value: mongo
        image: hiroki11hanada/stateful-unit-mongo:dev
        name: mongorepo
        ports:
        - containerPort: 27017
          name: mongo
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mongorepo
  namespace: hexagon
spec:
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 0
  selector:
    app: mongorepo
status:
  loadBalancer: {}

