---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    rca: ignore
  creationTimestamp: null
  name: cartredis
  namespace: hexagon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartredis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cartredis
    spec:
      containers:
      - env:
        - name: TRACING
          value: "false"
        image: hiroki11hanada/stateful-unit-redis:dev
        name: cartredis
        ports:
        - containerPort: 6379
          name: redis
        resources:
          limits:
            cpu: 125m
            memory: 256Mi
          requests:
            cpu: 70m
            memory: 200Mi
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: cartredis
  namespace: hexagon
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 0
  selector:
    app: cartredis
status:
  loadBalancer: {}

