---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  creationTimestamp: null
  labels:
    strimzi.io/cluster: my-cluster
  name: PlaceOrder
  namespace: kafka
spec:
  partitions: 1
  replicas: 1

