---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: recommendation
  namespace: hexagon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: recommendation
    spec:
      containers:
      - env:
        - name: TRACING
          value: "false"
        image: hiroki11hanada/service-unit:dev
        name: recommendation
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 450Mi
          requests:
            cpu: 100m
            memory: 220Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: recommendation-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: recommendation
  namespace: hexagon
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 0
  selector:
    app: recommendation
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    version: dev
    name: recommendation
    deployment:
      resources:
        requests:
          cpu: 100m
          memory: 220Mi
        limits:
          cpu: 200m
          memory: 450Mi
      env:
        - name: TRACING
          value: "false"
    adapters:
      - server:
          action: simpleRpc
          variant: grpc
          route: ListRecommendation
          payload:
            size: 50
        steps:
          - adapter:
              invocation:
                variant: grpc
                service: productcatalog
                action: simpleRpc
                route: ListProducts
                payload:
                  size: 0
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: recommendation-config
  namespace: hexagon

