version: dev
name: grpc-gateway
deployment:
  env:
  - name: LOG_LEVEL
    value: debug
adapters:
# grpc secondary adapters
- server:
    action: read
    variant: rest
    route: grpc
  tasks:
  - adapter:
      invocation:
        variant: grpc
        service: grpcserver
        action: simpleRpc
        route: get
    resiliency:
      isCritical: true
      retry:
        disabled: false
        backoffPolicy: exponential
        maxAttempt: 5
        initialBackoff: 1s
      circuitBreaker:
        disabled: true
      callTimeout: 15ms
