---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ad
  namespace: hexagon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ad
    spec:
      containers:
      - image: hiroki11hanada/service-unit:dev
        name: ad
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: ad-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ad
  namespace: hexagon
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 0
  selector:
    app: ad
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    version: dev
    name: ad
    adapters:
    - server:
        action: simpleRpc
        variant: grpc
        route: GetAds
      steps: []
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ad-config
  namespace: hexagon

