---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: checkout
  namespace: hexagon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: checkout
    spec:
      containers:
      - image: hiroki11hanada/service-unit:dev
        name: checkout
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: checkout-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: checkout
  namespace: hexagon
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 0
  selector:
    app: checkout
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    version: dev
    name: checkout
    adapters:
    - server:
        action: simpleRpc
        variant: grpc
        route: PlaceOrder
      steps:
      - adapter:
          invocation:
            variant: grpc
            service: cart
            action: simpleRpc
            route: GetCart
      - adapter:
          invocation:
            variant: grpc
            service: productcatalog
            action: simpleRpc
            route: GetProduct
      - adapter:
          invocation:
            variant: grpc
            service: currency
            action: simpleRpc
            route: Convert
      - adapter:
          invocation:
            variant: grpc
            service: shipping
            action: simpleRpc
            route: GetQuote
      - adapter:
          invocation:
            variant: grpc
            service: currency
            action: simpleRpc
            route: Convert
      - adapter:
          invocation:
            variant: grpc
            service: payment
            action: simpleRpc
            route: Charge
      - adapter:
          invocation:
            variant: grpc
            service: shipping
            action: simpleRpc
            route: ShipOrder
      - adapter:
          invocation:
            variant: grpc
            service: cart
            action: simpleRpc
            route: EmptyCart
      - adapter:
          invocation:
            variant: grpc
            service: email
            action: simpleRpc
            route: SendOrderConfirmation
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: checkout-config
  namespace: hexagon

