---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: frontend
  namespace: hexagon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: hiroki11hanada/service-unit:dev
        name: frontend
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: frontend-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: frontend
  namespace: hexagon
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 0
  selector:
    app: frontend
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    version: dev
    name: frontend
    adapters:
    - server:
        action: get
        variant: rest
        route: root
      steps:
      - adapter:
          invocation:
            variant: grpc
            service: currency
            action: simpleRpc
            route: GetSupportedCurrency
      - adapter:
          invocation:
            variant: grpc
            service: productcatalog
            action: simpleRpc
            route: ListProducts
      - adapter:
          invocation:
            variant: grpc
            service: cart
            action: simpleRpc
            route: GetCart
      - adapter:
          invocation:
            variant: grpc
            service: currency
            action: simpleRpc
            route: Convert
      - adapter:
          invocation:
            variant: grpc
            service: ad
            action: simpleRpc
            route: GetAds

    - server:
        action: get
        variant: rest
        route: product
      steps:
      - adapter:
          invocation:
            variant: grpc
            service: productcatalog
            action: simpleRpc
            route: GetProduct
      - adapter:
          invocation:
            variant: grpc
            service: currency
            action: simpleRpc
            route: GetSupportedCurrency
      - adapter:
          invocation:
            variant: grpc
            service: cart
            action: simpleRpc
            route: GetCart
      - adapter:
          invocation:
            variant: grpc
            service: currency
            action: simpleRpc
            route: Convert
      - adapter:
          invocation:
            variant: grpc
            service: recommendation
            action: simpleRpc
            route: ListRecommendation
      - adapter:
          invocation:
            variant: grpc
            service: ad
            action: simpleRpc
            route: GetAds

    - server:
        action: get
        variant: rest
        route: cart
      steps:
      - adapter:
          invocation:
            variant: grpc
            service: currency
            action: simpleRpc
            route: GetSupportedCurrency
      - adapter:
          invocation:
            variant: grpc
            service: cart
            action: simpleRpc
            route: GetCart
      - adapter:
          invocation:
            variant: grpc
            service: recommendation
            action: simpleRpc
            route: ListRecommendation
      - adapter:
          invocation:
            variant: grpc
            service: shipping
            action: simpleRpc
            route: GetQuote
      - adapter:
          invocation:
            variant: grpc
            service: currency
            action: simpleRpc
            route: Convert
      - adapter:
          invocation:
            variant: grpc
            service: productcatalog
            action: simpleRpc
            route: GetProduct
      - adapter:
          invocation:
            variant: grpc
            service: currency
            action: simpleRpc
            route: Convert

    - server:
        action: post
        variant: rest
        route: cart
      steps:
      - adapter:
          invocation:
            variant: grpc
            service: productcatalog
            action: simpleRpc
            route: GetProduct
      - adapter:
          invocation:
            variant: grpc
            service: cart
            action: simpleRpc
            route: AddItem

    - server:
        action: post
        variant: rest
        route: cart/empty
      steps:
      - adapter:
          invocation:
            variant: grpc
            service: cart
            action: simpleRpc
            route: EmptyCart

    - server:
        action: post
        variant: rest
        route: setCurrency
      steps: []

    - server:
        action: post
        variant: rest
        route: logout
      steps: []

    - server:
        action: post
        variant: rest
        route: cart/checkout
      steps:
      - adapter:
          invocation:
            variant: grpc
            service: checkout
            action: simpleRpc
            route: PlaceOrder
      - adapter:
          invocation:
            variant: grpc
            service: recommendation
            action: simpleRpc
            route: ListRecommendation
      - adapter:
          invocation:
            variant: grpc
            service: currency
            action: simpleRpc
            route: GetSupportedCurrency

    - server:
        action: get
        variant: rest
        route: static
      steps: []
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: frontend-config
  namespace: hexagon

