---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: gateway
  namespace: the-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway
    spec:
      containers:
      - image: hiroki11hanada/service-unit:dev
        name: gateway
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: gateway-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: gateway
  namespace: the-bench
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 0
  selector:
    app: gateway
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    version: dev
    name: gateway
    deployment:
      gateway: # load generator specific
        virtualUsers: 10
        duration: 60
    adapters:
    # # grpc secondary adapters
    # - server:
    #     action: read
    #     variant: rest
    #     route: grpc
    #     weight: 1 # load generator specific
    #   steps:
    #   - adapter:
    #       invocation:
    #         variant: grpc
    #         service: grpcserver
    #         action: simpleRpc
    #         route: get
    #   - adapter:
    #       invocation:
    #         variant: grpc
    #         service: grpcserver
    #         action: clientStream
    #         route: get
    #   - adapter:
    #       invocation:
    #         variant: grpc
    #         service: grpcserver
    #         action: serverStream
    #         route: get
    #   - adapter:
    #       invocation:
    #         variant: grpc
    #         service: grpcserver
    #         action: biStream
    #         route: get
    #
    # # http secondary adapters
    # - server:
    #     action: read
    #     variant: rest
    #     route: httprest
    #     weight: 1 # load generator specific
    #   steps:
    #   - adapter:
    #       invocation:
    #         variant: rest
    #         service: chain1
    #         action: read
    #         route: get
    #   - adapter:
    #       invocation:
    #         variant: rest
    #         service: chain1
    #         action: write
    #         route: post
    #         payload: large
    #
    # # mongo secondary adapter
    # - server:
    #     action: read
    #     variant: rest
    #     route: mongo
    #     weight: 1 # load generator specific
    #   steps:
    #   - adapter:
    #       repository:
    #         name: mongorepo
    #         variant: mongo
    #         action: read
    #         payload: small
    #   - adapter:
    #       repository:
    #         name: mongorepo
    #         variant: mongo
    #         action: write
    #         payload: large
    #
    # redis secondary adapters
    - server:
        action: read
        variant: rest
        route: redis
        weight: 1 # load generator specific
      steps:
      - adapter:
          repository:
            name: redisrepo
            variant: redis
            action: read
            payload: small
      - adapter:
          stressor:
            name: cpu
            variant: cpu
            duration: 10ms
            payload: small
      - adapter:
          repository:
            name: redisrepo
            variant: redis
            action: write
            payload: large
    #
    # # kafka secondary adapter
    # - server:
    #     action: read
    #     variant: rest
    #     route: produce
    #     weight: 1 # load generator specific
    #   steps:
    #   - adapter:
    #       producer:
    #         variant: kafka
    #         topic: topic1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: gateway-config
  namespace: the-bench

