---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: redis-gateway
  namespace: hexagon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-gateway
    spec:
      containers:
      - image: hiroki11hanada/service-unit:dev
        name: redis-gateway
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 125m
            memory: 64Mi
        volumeMounts:
        - mountPath: /app/config/
          name: config
      volumes:
      - configMap:
          items:
          - key: config
            path: service-unit.yaml
          name: redis-gateway-config
        name: config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: redis-gateway
  namespace: hexagon
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 0
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 0
  selector:
    app: redis-gateway
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  config: |
    version: dev
    name: redis-gateway
    # deployment:
    #   gateway: # load generator specific
    #     virtualUsers: 3
    #     duration: 60
    adapters:
    # redis secondary adapters
    - server:
        action: read
        variant: rest
        route: redis
        weight: 1 # load generator specific
      steps:
      - adapter:
          repository:
            name: redisrepo
            variant: redis
            action: read
            payload:
              variant: small

    # redis secondary adapters
    - server:
        action: write
        variant: rest
        route: redis
        weight: 1 # load generator specific
      steps:
      - adapter:
          repository:
            name: redisrepo
            variant: redis
            action: write
            payload:
              variant: large
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: redis-gateway-config
  namespace: hexagon

