name: Build docker images

on:
  push:
    branches:
      - "develop"
    tags:
      - "v*.*.*"
env:
  DOCKERHUB_USERNAME: hiroki11hanada

jobs:
  build-core-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - IMAGE_NAME: hexagon
            DOCKERFILE_PATH: ./build/service-unit/Dockerfile
          - IMAGE_NAME: hexagon-datagen
            DOCKERFILE_PATH: ./build/datagen/Dockerfile
          - IMAGE_NAME: hexagon-load-generator
            DOCKERFILE_PATH: ./build/load-generator/Dockerfile
          - IMAGE_NAME: hexagon-mongo
            DOCKERFILE_PATH: ./build/stateful-unit/mongo/Dockerfile
          - IMAGE_NAME: hexagon-redis
            DOCKERFILE_PATH: ./build/stateful-unit/redis/Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.DOCKERFILE_PATH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # two step builds are required for handling build dependencies
  build-dependent-images:
    needs: build-core-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - IMAGE_NAME: hexagon-mongo
            DOCKERFILE_PATH: ./build/stateful-unit/mongo/Dockerfile
            DEPENDENCY_IMAGE: hexagon-datagen
          - IMAGE_NAME: hexagon-redis
            DOCKERFILE_PATH: ./build/stateful-unit/redis/Dockerfile
            DEPENDENCY_IMAGE: hexagon-datagen

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      # Output the sha image tag that was pushed to the registry.
      # The script uses ./jq to parse the JSON output from the docker/metadata-action@v4 action.
      # See https://jqlang.github.io/jq/ for more information.
      - name: Output SHA image tag
        id: output_sha_image_tag
        env:
          DOCKER_METADATA: ${{ steps.meta.outputs.json}}
        run: |
          # pretty print the metadata
          echo $DOCKER_METADATA | jq '.'

          # get the image tag that contains 'sha-'
          image_tag=$(echo "$DOCKER_METADATA" | jq -r '.tags[] | select(. | test("sha-"))')
          echo $image_tag

          # get the sha from the image tag, for example: sha-1234567890abcdef1234567890abcdef12345678
          image_tag_sha=$(echo "$image_tag" | grep -o 'sha-[a-f0-9]\+')
          echo $image_tag_sha

          echo "image_tag_sha=$image_tag_sha" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.DOCKERFILE_PATH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDER_IMAGE=${{ env.DOCKERHUB_USERNAME }}/${{ matrix.DEPENDENCY_IMAGE }}:${{ steps.output_sha_image_tag.outputs }}
